CREATE DATABASE IF NOT EXISTS karangtaruna;
USE karangtaruna;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS berita (
  id INT AUTO_INCREMENT PRIMARY KEY,
  judul VARCHAR(255) NOT NULL,
  isi TEXT,
  tanggal DATE,
  gambar VARCHAR(255),
  status ENUM('publish', 'draft') DEFAULT 'publish',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS galeri (
  id INT AUTO_INCREMENT PRIMARY KEY,
  judul VARCHAR(255),
  gambar VARCHAR(255) NOT NULL,
  deskripsi TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS program (
  id INT AUTO_INCREMENT PRIMARY KEY,
  icon VARCHAR(50),
  judul VARCHAR(255) NOT NULL,
  deskripsi TEXT,
  jadwal VARCHAR(255),
  tipe ENUM('rutin', 'kalender') DEFAULT 'rutin',
  tanggal_mulai DATE,
  tanggal_selesai DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS umkm (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama_usaha VARCHAR(255) NOT NULL,
  pemilik VARCHAR(255),
  kategori VARCHAR(50),
  deskripsi TEXT,
  no_hp VARCHAR(20),
  gambar VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tanggal DATE NOT NULL,
  deskripsi VARCHAR(255),
  kategori VARCHAR(100),
  pemasukan DECIMAL(15,2) DEFAULT 0,
  pengeluaran DECIMAL(15,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pengurus (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(255) NOT NULL,
  jabatan VARCHAR(100),
  foto VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pendaftar (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama_lengkap VARCHAR(255) NOT NULL,
  usia INT,
  no_hp VARCHAR(20),
  alamat TEXT,
  pekerjaan VARCHAR(255),
  alasan_bergabung TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
