name = "karangtaruna"
main = "src/index.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./"
binding = "ASSETS"

[vars]
SUPABASE_URL = "https://passitfrdvixmazydrbc.supabase.co"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhc3NpdGZyZHZpeG1henlkcmJjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NDQwMDgzNywiZXhwIjoyMDk5OTc2ODM3fQ.Vb9sMnvRhmVtdbzIhPChC_DSCNMTvr1D176NMyEiv0s"
JWT_SECRET = "karangtaruna_secret_key_2026"
